import { NextRequest, NextResponse } from 'next/server';

/**
 * Demo Custom Tool: Business Insight Generator
 *
 * This demonstrates how custom tools work in MyMBA.
 * You can add this tool in the UI with:
 * - Name: business_insight_generator
 * - Endpoint: http://localhost:3000/api/demo-tool
 * - Auth: none
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { input, context } = body;

    // Parse the input to extract parameters
    const topic = typeof input === 'string' ? input : input?.topic || 'general business';

    // Generate insights based on the topic
    const insights = generateBusinessInsight(topic);

    return NextResponse.json({
      success: true,
      result: insights,
      metadata: {
        tool: 'business_insight_generator',
        timestamp: new Date().toISOString(),
        context: context || 'none',
      }
    });
  } catch (error) {
    console.error('Demo tool error:', error);
    return NextResponse.json(
      {
        error: 'Failed to generate insight',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

function generateBusinessInsight(topic: string): string {
  const insights: Record<string, string[]> = {
    marketing: [
      "Focus on content marketing - it generates 3x more leads than traditional advertising",
      "Personalization increases customer engagement by 80%",
      "Video content has 12x more shares than text and images combined",
      "Email marketing ROI averages $42 for every $1 spent",
    ],
    sales: [
      "80% of sales require 5+ follow-ups, but most reps stop after 2",
      "Social selling increases win rates by 5x compared to cold calling",
      "Leads respond 60% faster when contacted within 5 minutes",
      "Consultative selling increases close rates by 40%",
    ],
    finance: [
      "Cash flow problems cause 82% of small business failures",
      "Companies with formal budgeting grow 30% faster",
      "Reducing customer churn by 5% can increase profits by 25-95%",
      "Average B2B payment cycle is 47 days - optimize to improve cash flow",
    ],
    operations: [
      "Process automation can reduce operational costs by 30-50%",
      "Employee productivity increases 20% with proper training programs",
      "Quality control reduces defect costs by up to 40%",
      "Lean methodology can cut production time by 25-50%",
    ],
    strategy: [
      "Companies with clear strategies are 12% more profitable",
      "First-mover advantage exists in only 13% of industries",
      "Blue ocean strategy creates new market space instead of competing",
      "85% of strategic plans fail due to poor execution, not bad strategy",
    ],
  };

  // Find relevant category
  const lowerTopic = topic.toLowerCase();
  let category = 'strategy'; // default

  for (const [key, _] of Object.entries(insights)) {
    if (lowerTopic.includes(key)) {
      category = key;
      break;
    }
  }

  const categoryInsights = insights[category];
  const randomInsight = categoryInsights[Math.floor(Math.random() * categoryInsights.length)];

  return `💡 **Business Insight on "${topic}"**

${randomInsight}

**Category:** ${category.charAt(0).toUpperCase() + category.slice(1)}
**Applicability:** ${getApplicability(category)}

**Recommended Actions:**
${getRecommendedActions(category)}

---
✓ Generated by Business Insight Generator (Demo Custom Tool)`;
}

function getApplicability(category: string): string {
  const applicability: Record<string, string> = {
    marketing: 'B2B and B2C companies, all sizes',
    sales: 'Enterprise, SMB, and startup sales teams',
    finance: 'All businesses, especially critical for startups and SMBs',
    operations: 'Manufacturing, service, and tech companies',
    strategy: 'C-level executives and business leaders',
  };
  return applicability[category] || 'General business applicability';
}

function getRecommendedActions(category: string): string {
  const actions: Record<string, string> = {
    marketing: '• Audit current channels\n• Test personalization strategies\n• Invest in video content',
    sales: '• Implement follow-up automation\n• Train team on consultative selling\n• Reduce response time',
    finance: '• Create 90-day cash flow forecast\n• Review payment terms\n• Set up automated invoicing',
    operations: '• Map current processes\n• Identify automation opportunities\n• Implement quality metrics',
    strategy: '• Define clear 3-year vision\n• Establish quarterly OKRs\n• Create execution scorecard',
  };
  return actions[category] || '• Analyze current state\n• Define goals\n• Create action plan';
}
